
// This file has been generated by the GUI designer. Do not modify.
namespace IngDelSw
{
	public partial class Authentication
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget IngDelSw.Authentication
			this.Name = "IngDelSw.Authentication";
			this.Title = global::Mono.Unix.Catalog.GetString ("Authentication");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
